version: "3.9"

services:
  backend:
    build: ./backend
    container_name: eventhub-backend
    volumes:
      - db_data:/app
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: eventhub-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
